// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztwhbrkqyfvueiwjptfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0d2hicmtxeWZ2dWVpd2pwdGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MjMyMTQsImV4cCI6MjA4ODk5OTIxNH0.xb7mo2wI7XZRoLSCt9LHf8CW1L2vYcUeYurW6g0K1bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});